# Generated by Django 5.0.4 on 2024-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty_app', '0003_chatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
